<a href="https://colab.research.google.com/github/aloocoder/learn_pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd

print(torch.__version__)

2.3.1+cu121


###introduction to tensors

creating tensors

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,7],
                       [7,7]])
MATRIX

tensor([[7, 7],
        [7, 7]])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 7])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0][1]

tensor([4, 5, 6])

In [ ]:
TENSOR[0][1][2]

tensor(6)

###random tensors

In [ ]:
#raodom tensor of size (x,y)
random_tensor = torch.rand(2,3)

In [ ]:
random_tensor

tensor([[0.1126, 0.3111, 0.0727],
        [0.9093, 0.1198, 0.3564]])

In [ ]:
random_tensor.ndim

2

In [ ]:
##random tensor with similar shape to a image tensor
random_image_tensor = torch.rand(size = (3,64,64)) ##color , height, width
random_image_tensor.shape, random_image_tensor.ndim


(torch.Size([3, 64, 64]), 3)

In [ ]:
zeros = torch.zeros(size = (2,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones = torch.ones(size = (1,2))
ones

tensor([[1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
2*ones

tensor([[2., 2.]])

##creating a range of tensors and alike tensors

In [ ]:
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor  = torch.tensor([3.0, 6.0, 9.0],
                                dtype = None, ## the datatype of the tensor
                                device = None, ## the device on which the tensor is (GPU/CPU)
                                requires_grad = False ) ## required to track the gradient calculation
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
##convert it to 16bit tensor
float_64_tensor = float_32_tensor.type(torch.float64)
float_64_tensor.dtype

torch.float64

In [ ]:
float_64_tensor*float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

##matrix multiplication

In [ ]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor@tensor

tensor(14)

In [ ]:
#transpose of a matrix

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A,(tensor_B.T))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Tensor aggregation

In [ ]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
#find the min
x.min(), torch.min(x)

(tensor(1), tensor(1))

In [ ]:
#find the mean
# torch.mean(x)
#note the torch.mean() requires a FLOAT32 type datatype

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
#sum of tensor
torch.sum(x)

tensor(460)

positional min and max

In [ ]:
#argmin() retrn the position of the where the minimum value occurs in the tensor
x.argmin()

tensor(0)

In [ ]:
#argmax() returs the poition of wher the max value occurs in the tensor
x.argmax()

tensor(9)

#reshaping, squezzing , stacking and unsqueezing

In [ ]:
import torch
x = torch.arange(1.,11)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
#add an extra dimension
y = x.reshape(2,5)
y, y.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
#change the view
# create a new tensor same as x but with diff dimension
#changing the view tensor changes the main tensor as well ,as they share the same memorry location
z = x.view(2,5)
z

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [ ]:
z[0][0] = 20 #changing z changed x
z,x

(tensor([[20.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 tensor([20.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
x[0] = 1 #changing x changed z
z,x

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
#stack tensors on top of each other
x_stacked = torch.stack([x,x], dim = 1)
x_stacked, x
#dim = 0 -> vStack and dim = 1 -> hStack

(tensor([[ 1.,  1.],
         [ 2.,  2.],
         [ 3.,  3.],
         [ 4.,  4.],
         [ 5.,  5.],
         [ 6.,  6.],
         [ 7.,  7.],
         [ 8.,  8.],
         [ 9.,  9.],
         [10., 10.]]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
#squeeze the tensor
#removes all dimension '1' from the target tensor
#changing the squeeze tensor changes the main tensor as well ,as they share the same memorry location
x_new = torch.zeros(2,1,2,1,2)

In [ ]:
y = x_new.squeeze()
y.shape

torch.Size([2, 2, 2])

In [ ]:
y = x_new.squeeze(1)
y.shape

torch.Size([2, 2, 1, 2])

In [ ]:
y = x_new.squeeze(0)
y.shape

torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = x_new.squeeze((1,2,3)) #removes the dimesions at the given index if they have dim =1
y.shape

torch.Size([2, 2, 2])

In [ ]:
#unsqueeze  - adds a single dimension to a target tensor at a specific dim(dimension)
y = torch.arange(1,11,1)
y, y.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [ ]:
x_new = y.unsqueeze(dim = 0)
x_new, x_new.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [ ]:
x_new = y.unsqueeze(dim = 1)
x_new, x_new.shape

(tensor([[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10]]),
 torch.Size([10, 1]))

In [ ]:
#torch.permute - rearrange the dimension of the target tensor in a specified order
#shares the same address as the orignal tensor
x_new  = torch.rand(size = (224,224,3))
print(x_new.shape)

x_permute = x_new.permute(2,0,1)
print(x_permute.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


####indexing

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0], x[0][1], x[0][2]

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

##pytorch tensors and numpy

In [ ]:
import torch
import numpy as np

array = np.arange(1.0,11.0)
tensor = torch.from_numpy(array)
array, tensor
#numpy default dataype is float64 and pytorch reflects it unless specified

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

In [ ]:
#changing the value of the array
array = array + 1
array,tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

In [ ]:
#tensor to numpy
tensor = torch.ones(10)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor
#they donot share the same address

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##reproducibilty

the concept of random seed it flavors that randomness

In [ ]:
import torch

rand_a = torch.rand(3,4)
rand_b = torch.rand(3,4)

print(rand_a)
print(rand_b)
print(rand_a == rand_b)

tensor([[0.4694, 0.7748, 0.2125, 0.0361],
        [0.0775, 0.4931, 0.5916, 0.2015],
        [0.1594, 0.0743, 0.2084, 0.9736]])
tensor([[0.5189, 0.6828, 0.2392, 0.5448],
        [0.3844, 0.6475, 0.0397, 0.5523],
        [0.8425, 0.5946, 0.6410, 0.7101]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
import torch

random_seed = 42

torch.manual_seed(random_seed)
rand_a = torch.rand(3,4)

torch.manual_seed(random_seed)
rand_b = torch.rand(3,4)

print(rand_a==rand_b)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##runnin on GPU

In [ ]:
import torch
torch.cuda.is_available()

False

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'